name: Build and Release

on:
  release:
    types: [published]

jobs:
  publish-dotnet:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_dir: out
            artifact_name: out.zip
            asset_name: binaries-linux-amd64.zip
          - os: windows-latest
            build_dir: out
            artifact_name: out.zip
            asset_name: binaries-windows-amd64.zip

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: dotnet publish -o ${{ matrix.build_dir }}
    - name: Zip output directory
      uses: thedoctor0/zip-release@master 
      with:
        type: 'zip'
        filename: ${{ matrix.artifact_name }}
        directory: ${{ matrix.build_dir }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.build_dir}}/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

  publish-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git repo
        uses: actions/checkout@v2
      - name: Compile latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload pdf to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.pdf
          asset_name: main.pdf
          tag: ${{ github.ref }} 